worker_processes 1;

events {
  worker_connections 1024;
}

http {
  include mime.types;

  server {
    listen 3000;

    root /usr/share/nginx/html/public;
    index index.html;

    location /api/ {
      proxy_pass http://backend:4000/;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }

    location /src/ {
      alias /usr/share/nginx/html/src/;
    }

    error_page 404 /offline.html;
  }
}